from typing import Literal

from tables import Table


class Index:
    prefix: str = Literal['idx']
    max_name_length: int = Literal[30]
    index_name: str = ...
    name: str = ...
    fields: list[str] = ...
    index_name: str = ...

    def __init__(self, name: str, *fields: str) -> None: ...

    def __repr__(self) -> str: ...
    def as_sql(self, table: Table) -> str: ...
