import dataclasses
from typing import (Any, Callable, Dict, Literal, Optional, Tuple, Union,
                    override)

from database.base import RelationshipMap
from database.tables.base import Table
from expressions import Q

from lorelie.backends import SQLiteBackend
from lorelie.database.functions.base import Functions
from lorelie.queries import QuerySet

@dataclasses.dataclass
class SelectMap:
    select: type[SelectNode] = None
    where: type[WhereNode] = None
    order_by: type[OrderByNode] = None
    limit: int = None
    groupby: list = None
    having: list = None

    def __setitem__(self, name: str,  value: Any) -> None: ...

    @property
    def should_resolve_map(self) -> bool: ...

    def resolve(self, backend) -> list[str]: ...
    def add_ordering(self, other: OrderByNode) -> None: ...


class RawSQL:
    nodes: list[str, BaseNode] = ...
    backend: SQLiteBackend = ...
    resolve_select: bool = ...
    select_map: SelectMap = ...

    def __init__(
        self, backend: SQLiteBackend,
        *
        nodes: Union[str, BaseNode]
    ) -> None: ...

    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __iter__(self) -> list[str]: ...
    def __eq__(self, value) -> bool: ...
    def as_sql(self) -> list[str]: ...


class ComplexNode:
    def __init__(self, *nodes: BaseNode) -> None: ...
    def __repr__(self) -> str: ...
    def __add__(self, node) -> ComplexNode: ...
    def __contains__(self, node) -> bool: ...

    def as_sql(self, backend) -> RawSQL: ...


class BaseNode:
    template_sql: str = ...
    table: Table = ...
    fields: list = ...

    def __init__(
        self,
        table: Optional[Table] = ...,
        fields: Optional[list[str]] = ...
    ) -> None: ...

    def __repr__(self) -> str: ...
    def __add__(self, node: BaseNode) -> ComplexNode: ...
    def __eq__(self, node: BaseNode) -> bool: ...
    def __contains__(self, value: BaseNode) -> bool: ...
    def __and__(self, node: BaseNode) -> BaseNode: ...

    @property
    def node_name(self) -> str: ...

    def as_sql(self, backend: SQLiteBackend) -> list[str]: ...


class SelectNode(BaseNode):
    distinct: bool = Literal[False]
    limit: Optional[int] = ...
    view_name: Optional[str] = ...

    def __init__(
        self,
        table: Table,
        *fields: str,
        distinct: Optional[bool] = ...,
        limit: Optional[int] = ...,
        view_name: Optional[str] = ...
    ) -> None: ...

    @override
    def __call__(
        self,
        *fields: str,
        **kwargs
    ) -> SelectNode: ...


class WhereNode(BaseNode):
    expressions: dict[str, Functions] = ...
    func_expressions: list[Functions] = ...
    invert: bool = Literal[False]

    def __init__(self, *args: Functions, **expressions) -> None: ...

    @override
    def __call__(self, *args: Functions, **expressions) -> WhereNode: ...

    def __invert__(self) -> WhereNode: ...


class OrderByNode(BaseNode):
    ascending: set = ...
    descending: set = ...
    cached_fields: list[str] = ...

    def __init__(self, table: Table, *fields: str) -> None: ...
    def __hash__(self) -> int: ...
    def __and__(self, node: OrderByNode) -> OrderByNode: ...

    @staticmethod
    def construct_sql(
        backend: SQLiteBackend,
        field: str,
        ascending: Optional[bool] = ...
    ) -> Union[str, None]: ...


class UpdateNode(BaseNode):
    where_args: Tuple[Union[str, Q]] = ...
    where_expressions: Dict[str, Union[Q, Any]] = ...
    update_defaults: Dict[str, Any] = ...

    def __init__(
        self,
        table: Table,
        update_defaults: Dict[str, Any],
        *where_args: Q,
        **where_expressions: str
    ) -> None: ...


class DeleteNode(BaseNode):
    where_args: Tuple[Union[str, Q]] = ...
    where_expressions: Dict[str, Union[Q, Any]] = ...
    order_by: list[str] = ...
    limit: Optional[int] = ...

    def __init__(
        self,
        table: Table,
        *where_args: Q,
        order_by: Optional[list[str]] = ...,
        limit: Optional[int] = ...,
        **where_expressions: str
    ) -> None: ...

    @override
    def as_sql(self, backend: SQLiteBackend) -> list[str]: ...


class InsertNode(BaseNode):
    bactch_insert_sql: str = ...
    insert_values: dict[str, Union[int, float, Callable[..., Any]]] = ...
    returning: list[str] = ...
    batch_values: list[dict[str, Union[int, float, Callable[..., Any]]]] = ...

    def __init__(
        self,
        table: Table,
        batch_values: Optional[list[dict[str, Any]]] = ...,
        insert_values: Optional[dict[str, Any]] = ...,
        returning: Optional[list[str]] = ...
    ) -> None: ...


class JoinNode(BaseNode):
    cross_join: str = ...
    full_outer_join: str = ...
    join_type: str = ...
    relationship_map: Any = ...

    def __init__(
        self,
        table: str,
        relationship_map: RelationshipMap,
        join_type: Optional[str] = ...
    ) -> None: ...


class IntersectNode(BaseNode):
    left_select: SelectNode = ...
    right_select: SelectNode = ...

    def __init__(
        self, 
        left_select: SelectNode, 
        right_select: SelectNode
    ) -> None: ...


class ViewNode(BaseNode):
    name: str = ...
    temporary: bool = Literal[False]
    queryset: QuerySet = ...

    def __init__(
        self,
        name: str,
        queryset: QuerySet,
        temporary: Optional[bool] = ...
    ) -> None: ...
