from lorelie.queries import QuerySet
from lorelie.database.tables.base import Table

class View:
    name: str = ...
    queryset: QuerySet = ...
    temporary: bool = ...
    fields: list[str] = ...

    def __init__(
        self,
        name: str,
        queryset: QuerySet,
        temporary: bool = ...,
        fields: list[str] = ...
    ) -> None: ...

    def __call__(self, table: Table) -> QuerySet: ...
