from typing import Any, Dict, override

from lorelie.backends import SQLiteBackend
from lorelie.expressions import Q
from lorelie.fields.base import Field


class BaseConstraint:
    template_sql: str = ...
    prefix: str = ...
    name: str = ...
    constraint_name: str = ...
    base_errors: Dict[str, str] = ...

    def __init__(self, name: str) -> None: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, instance: BaseConstraint) -> bool: ...

    def as_sql(self, backend: SQLiteBackend) -> str: ...


class CheckConstraint(BaseConstraint):
    name: str = ...
    condition: Q = ...

    def __init__(self, name: str, condition: Q) -> None: ...

    @override
    def as_sql(self, backend: SQLiteBackend) -> str: ...


class UniqueConstraint(BaseConstraint):
    fields: list[str] = ...

    def __init__(self, name: str, *, fields: list[str] = ...) -> None: ...

    @override
    def as_sql(self, backend: SQLiteBackend) -> str: ...


class MinMaxMixin:
    limit: int = ...
    field: Field = ...

    def __init__(self, limit: int, field: Field) -> None: ...


class MaxLengthConstraint(MinMaxMixin, CheckConstraint):
    max_length: int = ...
    length_sql: str = ...

    @override
    def as_sql(self, backend: SQLiteBackend) -> str: ...


class MinValueConstraint(MinMaxMixin, BaseConstraint):
    @override
    def as_sql(self, backend: SQLiteBackend) -> str: ...


class MaxValueConstraint(MinValueConstraint):
    ...
