from typing import Any

from lorelie.backends import SQLiteBackend


class CheckConstraint:
    name: str = ...
    fields: list[str] = ...

    def __init__(self, name: str, *, fields: list[str] = ...) -> None: ...

    def as_sql(self, backend: SQLiteBackend) -> str: ...


class UniqueConstraint:
    UNIQUE: str = ...

    def __init__(self, name: str, *, fields: list[str] = ...) -> None: ...

    def as_sql(self, backend: SQLiteBackend) -> str: ...


class MaxLengthConstraint(CheckConstraint):
    max_length: int = ...

    def __init__(self, fields: list[str] = ...): ...
    def __call__(self, value: Any): ...

    def as_sql(self, backend: SQLiteBackend) -> str: ...
