from typing import Any, Callable, Tuple, Type, Union

from kryptone.db.tables import Table

class Field:
    python_type: Type[Union[str, bool, list, dict]] = ...
    base_validators: list = ...
    name: str = ...
    null: bool = ...
    primary_key: bool = ...
    default: Any = ...
    unique: bool = ...
    table: Table = ...
    max_length: int = ...,
    base_field_parameters: dict[str, bool] = ...
    base_validators: list[Callable[[Union[str, int]], None]]

    def __init__(
        self,
        name: str,
        *,
        max_length: int = ...,
        null: bool = ...,
        primary_key: bool = ...,
        default: Any = ...,
        unique: bool = ...,
        validators: list[Callable[[str], None]] = ...
    ) -> None: ...

    def __repr__(self) -> str: ...

    def __hash__(self) -> int: ...
    def __eq__(self, value: str) -> bool: ...

    @property
    def field_type(self) -> str: ...

    @classmethod
    def create(
        cls,
        name: str,
        params: list[str],
        verbose_name: str = ...
    ) -> Field: ...

    def to_python(self, data: Any) -> Any: ...
    def to_database(self, data: Any) -> str: ...
    def field_parameters(self) -> list[str]: ...
    def prepare(self, table: Table) -> None: ...
    def deconstruct(self) -> Tuple[str, list[str]]: ...


class CharField(Field):
    ...


class IntegerField(Field):
    python_type: Type[int] = ...
    min_value: int = ...
    max_value: int = ...

    def __init__(
        self, 
        name: str, 
        *, 
        min_value: int= ...,
        max_value: int=...,
        **kwargs
    ) -> None: ...


class JSONField(Field):
    python_type: Type[dict] = ...


class BooleanField(Field):
    truth_types: list[str] = ...
    false_types: list[str] = ...


class AutoField(Field):
    python_type : Type[int] = ...
    
    def __init__(self):
        self.base_field_parameters['auto increment'] = True
        super().__init__('id', primary_key=True)
