from typing import Any, Literal, NamedTuple, OrderedDict, Type, Union

import pandas

from lorelie.backends import BaseRow, SQLiteBackend
from lorelie.constraints import CheckConstraint
from lorelie.fields import Field
from lorelie.functions import Functions
from lorelie.indexes import Index
from lorelie.migrations import Migrations
from lorelie.queries import Query, QuerySet


class BaseTable(type):
    def __new__(cls, name: str, bases: tuple, attrs: dict) -> type: ...
    @classmethod
    def prepare(cls, table: type) -> None: ...


class AbstractTable(metaclass=BaseTable):
    query_class: Type[Query] = ...
    backend_class: Type[SQLiteBackend] = ...
    backend: SQLiteBackend = ...
    is_prepared: bool = Literal[False]

    def __init__(
        self,
        database_name: str = ...,
        inline_build: bool = ...
    ) -> None: ...

    def __hash__(self) -> int: ...
    def __eq__(self, value: Any) -> bool: ...

    def validate_values(self, fields, values) -> Any: ...
    # def all(self) -> list[BaseRow]: ...
    # def filter(self, **kwargs) -> list[BaseRow]: ...
    # def first(self) -> BaseRow: ...
    # def last(self) -> BaseRow: ...
    # def create(self, **kwargs) -> BaseRow: ...
    # def bulk_create(
    #     self,
    #     objs: List[Union[dict, NamedTuple]]
    # ) -> List[BaseRow]: ...
    # def get(self, **kwargs) -> Union[BaseRow, None]: ...
    # def annotate(self, **kwargs: Functions) -> QuerySet: ...
    # def order_by(self, *fields: str) -> list[BaseRow]: ...


class Table(AbstractTable):
    fields_map: OrderedDict[str, Field] = ...
    name: str = ...
    query: Query = ...
    indexes: list[str] = ...
    field_names: list[str] = ...

    def __init__(
        self,
        name: str,
        *,
        database_name: str = ...,
        inline_build: bool = ...,
        fields: list[Field] = ...,
        index: list[Index],
        constraints: list[CheckConstraint]
    ) -> None: ...

    def __repr__(self) -> str: ...

    def has_field(self, name: str) -> bool: ...
    def create_table_sql(self, fields: list[str]) -> list[str]: ...
    def drop_table_sql(self, name: str) -> list[str]: ...
    def build_field_parameters(self) -> list[str]: ...
    def prepare(self) -> None: ...


class Databases:
    database_map: OrderedDict[str, Database] = ...

    def __init__(self) -> None: ...
    def __getitem__(self, name: str) -> Database: ...

    def register(self, database: Database) -> None: ...


databases: Databases


class DatabaseManager:
    table_map: dict[str, Table] = ...
    def __init__(self) -> None: ...

    def __get__(
        self,
        instance: Database,
        cls: Type[Database] = ...
    ) -> DatabaseManager: ...
    def __repr__(self) -> str: ...

    def first(self, table: str) -> BaseRow: ...
    def last(self, table: str) -> BaseRow: ...
    def all(self, table: str) -> list[BaseRow]: ...
    def create(self, table: str, **kwargs) -> BaseRow: ...
    def filter(self, table: str, **kwargs) -> list[BaseRow]: ...
    def get(self, table: str, **kwargs) -> BaseRow: ...
    def annotate(self, table: str, **kwargs) -> list[BaseRow]: ...
    def as_values(self, table: str, *args: str) -> list[dict[str, Any]]: ...
    def as_dataframe(self, table: str, **kwarg) -> pandas.DataFrame: ...


class Database:
    migrations: Migrations = ...
    migrations_class: Type[Migrations] = ...
    table_map: dict[str, Table] = ...
    database_name: str = ...
    table_instances: list[Table] = ...
    objects: DatabaseManager = ...

    def __init__(self, name: str, *tables: Table): ...
    def __repr__(self) -> str: ...
    def __getitem__(self, table_name: str) -> Table: ...

    def get_table(self, table_name: str) -> Table: ...
    def make_migrations(self) -> None: ...
    def migrate(self) -> None: ...
