from dataclasses import dataclass

from lorelie.database.tables.base import Table
from lorelie.fields.base import Field


@dataclass
class Column:
    field: Field
    index: int = 0
    name: str = None
    full_column_name: str = None
    double_relation: bool = False

    def __post_init__(self) -> None: ...
    def __str__(self) -> str: ...
    def __eq__(self, item) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...

    @property
    def is_foreign_column(self) -> bool: ...

    @property
    def table(self) -> Table: ...

    @property
    def asc(self) -> str: ...

    @property
    def desc(self) -> str: ...

    def prepare(self) -> None: ...
