import sqlite3
from typing import Literal

from lorelie.backends import SQLiteBackend


class Functions:
    field_name: str = ...
    backend: SQLiteBackend = ...
    template_sql: str = ...
    allow_aggregration: bool = Literal[False]

    def __init__(self, field_name: str) -> None: ...
    def __repr__(self) -> str: ...

    @property
    def alias_field_name(self) -> str: ...

    @staticmethod
    def create_function(connection: sqlite3.Connection) -> None: ...

    @property
    def internal_type(self) -> Literal['function']: ...

    def as_sql(self, backend: SQLiteBackend) -> list[str]: ...
